### ISSUE TITLE
Linha do Oeste: correção de paragens

### ISSUE THREAD

**Issue by ScriptForAll** [carrismetropolitana/datasets#1]
Boa noite.

Notei os seguintes problemas nas paragens adjacentes à linha do Oeste:
- **Apeadeiro do Telhal** encontra-se encerrada. As paragens 170366 e 170365 deverão deixar de fazer menção ao comboio.
-  **Estação de Sabugo**. As paragens 171115 e 171116 , embora um pouco distantes, fazem a correspondência à ferrovia que não está descrita.
- **Apeadeiro de Pedra Furada**. As paragens 172411 e 172412 não fazem menção ao apeadeiro.
- **Apeadeiro de Jerumelo**. As paragens 200117 e 200118 não fazem menção ao apeadeiro.

**Comment by inesclemente** [comment]
Boa tarde,
Agradecemos as notas e informamos que as situações já se encontram corrigidas.
Obrigada
